### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by ProxyDorduran** [dorduran/GitHubActions#1]
I think it looks better if the main title is a bit more orange.

The style rule could be changed like this:

```css

h1 {
  color: #f59d04;
}

```
